___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>
___

In [414]:
import numpy as np

## Indexing

In [415]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [416]:
a[1]

1

In [417]:
a[-1]

5

In [418]:
# Slices like python lists

a[2:4]

array([2, 3])

In [419]:
a[-2:]

array([4, 5])

In [420]:
a[::2]

array([0, 2, 4])

### Setting values

In [421]:
a

array([0, 1, 2, 3, 4, 5])

#### Broadcasting

In [422]:
# Setting a value with index range (Broadcasting)
a[0:4] = 9

a

array([9, 9, 9, 9, 4, 5])

#### Views & Slices

In [423]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0, 11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [424]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [425]:
# Change Slice
slice_of_arr[:] = 99

# Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [426]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Copy

### Python list
```py
a = [1, 2, 3]
b = a           # Do not copy
b = a[:]        # Copy
b = a.copy()    # Copy
```

### NumPy array
```py
a = np.array([1, 2, 3])
b = a           # Do not copy
b = a[:]        # Do not copy /!\
b = a.copy()    # Copy
```

In [427]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

### Multiple dimensions indexing

In [428]:
a_2d = np.arange(12).reshape((3, -1))
a_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [429]:
a_2d[1]

array([4, 5, 6, 7])

In [430]:
# We separate dimensions by comma:
# 	a_2d[row, column]

a_2d[1, 0]

4

In [431]:
# we can apply our previous indexing methods
a_2d[: , 2]

array([ 2,  6, 10])

![NumPy Indexing](https://numpy.org/doc/1.25/_images/np_matrix_indexing.png)

#### RGB to BGR

In [432]:
a = np.arange(24).reshape((2, 4, 3))
a[:,:,0] = 0
a[:,:,1] = 1
a[:,:,2] = 2
a

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [433]:
a = a[:,:,[2,1,0]]
a

array([[[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]],

       [[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]]])

### Ellipsis

In [434]:
a = np.arange(120).reshape(2, 3, 4, 5)
a

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [435]:
a[:, :, :, 0]

array([[[  0,   5,  10,  15],
        [ 20,  25,  30,  35],
        [ 40,  45,  50,  55]],

       [[ 60,  65,  70,  75],
        [ 80,  85,  90,  95],
        [100, 105, 110, 115]]])

In [436]:
a[..., 0]

array([[[  0,   5,  10,  15],
        [ 20,  25,  30,  35],
        [ 40,  45,  50,  55]],

       [[ 60,  65,  70,  75],
        [ 80,  85,  90,  95],
        [100, 105, 110, 115]]])

In [437]:
a[0, :, :, 0]

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [438]:
a[0, ..., 0]

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

### Fancy indexing:

In [441]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [442]:
# Fancy indexing: 
#   indexing with an array of the desired indices

a[[1, 2, -1]]

array([1, 2, 5])

### Boolean indexing:

In [ ]:
# Boolean indexing

a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[ a > 2 ]

array([3, 4, 5, 6, 7, 8, 9])

Let's break it down:

In [443]:
a > 2

array([False, False, False,  True,  True,  True])

In [444]:
bool_arr = a > 2
a[bool_arr]

array([3, 4, 5])

In [ ]:
# Invert
a[ ~(a == 2) ]

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Multiple conditions with AND
a[(a > 2) & (a < 7)]

array([3, 4, 5, 6])

In [ ]:
# Multiple conditions with OR
a[ (a < 2) | (a > 7) ]

array([0, 1, 8, 9])

In [ ]:
a[ (a < 2) | (a > 7) ]

array([0, 1, 8, 9])

In [ ]:
# /!\ 
#   The () are not optional 
#   when there are multiple conditions

# a[ a < 2 | a > 7 ]

In [ ]:
value_if_true = 12
value_if_false = -3

np.where(
    a < 4, 
    value_if_true,
    value_if_false
)

array([12, 12, 12, 12, -3, -3, -3, -3, -3, -3])