___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>
___

In [3]:
import numpy as np

## Operations

In [4]:
a = np.full((4,), 10, dtype=float)
a

array([10., 10., 10., 10.])

In [5]:
b = np.full_like(a, 2)
b

array([2., 2., 2., 2.])

### Basic operations


In [6]:
a + b

array([12., 12., 12., 12.])

In [7]:
a * b

array([20., 20., 20., 20.])

In [8]:
a / b

array([5., 5., 5., 5.])

In [10]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [12]:
c / c

/tmp/ipykernel_3242454/1934242309.py:1: RuntimeWarning: invalid value encountered in divide
  c / c


array([nan,  1.,  1.,  1.])

In [ ]:
a // b

array([5., 5., 5., 5.])

### Broadcasting

In [ ]:
a = np.arange(1, 4)
a

array([1, 2, 3])

In [ ]:
a * 2

array([2, 4, 6])


![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [ ]:
a + 1

array([2, 3, 4])

In [ ]:
a / 2

array([0.5, 1. , 1.5])

In [ ]:
a // 2

array([0, 1, 1])

### Advanced operations

In [ ]:
a ** 2

array([1, 4, 9])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [13]:
np.sin(a)

array([-0.54402111, -0.54402111, -0.54402111, -0.54402111])

#### Dot product

![](https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/matrix-representation-of-dot-product-1626103121.png)

In [ ]:
a = np.arange(1, 11)
b = np.arange(4, 14)

np.dot(a, b)

550

In [ ]:
a = np.arange(0, 3, .7)
a

array([0. , 0.7, 1.4, 2.1, 2.8])

In [ ]:
np.floor(a)     # Rounds to lower integer

array([0., 0., 1., 2., 2.])

In [ ]:
np.ceil(a)      # Rounds to upper integer

array([0., 1., 2., 3., 3.])

In [ ]:
np.round(a)     # Rounds to nearest integer

array([0., 1., 1., 2., 3.])

In [ ]:
# Matrix multiplication

a_2d = np.arange(12).reshape(3, -1)
b_2d = np.arange(12).reshape(-1, 3)

print(f"{a_2d.shape = }")
print(f"{b_2d.shape = }")

np.matmul(      # is equivalent to `a_2d @ b_2d``
    a_2d,
    b_2d
)

a_2d.shape = (3, 4)
b_2d.shape = (4, 3)


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

## Statistics

In [ ]:
a = np.arange(12, dtype=float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
a.max()

11.0

In [ ]:
a.min()

0.0

In [ ]:
a.argmax()

11

In [ ]:
a.argmin()

0

### Sum

$$
\sum_{i=1}^n x_i
$$

In [ ]:
a.sum()

66.0

### Mean

$$
\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i
$$

In [ ]:
a.mean()

5.5

### Standard deviation

$$
\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^n (x_i - \bar{x})^2}
$$

In [ ]:
a.std()

3.452052529534663

### Variance

$$
\sigma^2 = \frac{1}{n}\sum_{i=1}^n (x_i - \bar{x})^2
$$

In [ ]:
a.var()

11.916666666666666

### Axis argument
![](https://miro.medium.com/v2/resize:fit:720/format:webp/1*jmXqsVUNaBaUsBAkHgqb3A.png)

In [ ]:
a_3d = np.arange(24).reshape(2, 3, 4)
a_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a_3d.sum()

276

In [ ]:
a_3d.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a_3d.sum(axis=1)


array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
a_3d.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## Numpy special values

In [ ]:
np.NaN

nan

In [ ]:
np.NaN == np.NaN

False

In [ ]:
np.inf

inf

In [ ]:
np.inf * -1

-inf

###  It's best to avoid rank one array 

Rank one arrays are arrays with (n,) shapes 

#### Problematic example

In [ ]:
a = np.random.randn(5)
a

array([ 0.87381718,  0.03508498,  0.62967074, -2.43129397,  0.04250259])

In [ ]:
a.shape

(5,)

In [ ]:
# Tranpose gives back the same array on rank one error, 
#   this is source error
a.T

array([ 0.87381718,  0.03508498,  0.62967074, -2.43129397,  0.04250259])

In [ ]:
np.dot(a, a.T)

7.074269519247207

#### Expected behavior

In [ ]:
a_2d = a.copy().reshape((5, 1))
a_2d

array([[ 0.87381718],
       [ 0.03508498],
       [ 0.62967074],
       [-2.43129397],
       [ 0.04250259]])

In [ ]:
a_2d.shape

(5, 1)

In [ ]:
a_2d.T

array([[ 0.87381718,  0.03508498,  0.62967074, -2.43129397,  0.04250259]])

In [ ]:
np.dot(a_2d, a_2d.T)

array([[ 7.63556470e-01,  3.06578605e-02,  5.50217116e-01,
        -2.12450645e+00,  3.71394906e-02],
       [ 3.06578605e-02,  1.23095599e-03,  2.20919870e-02,
        -8.53019062e-02,  1.49120251e-03],
       [ 5.50217116e-01,  2.20919870e-02,  3.96485246e-01,
        -1.53091468e+00,  2.67626354e-02],
       [-2.12450645e+00, -8.53019062e-02, -1.53091468e+00,
         5.91119038e+00, -1.03336283e-01],
       [ 3.71394906e-02,  1.49120251e-03,  2.67626354e-02,
        -1.03336283e-01,  1.80646988e-03]])

#### Function to solve the problem of shape (n,)

In [14]:
def add_dimension_to_rank_one_array(a: np.ndarray):
    if len(a.shape) == 1:       # Check if rank one array
        a = a.reshape((1, -1))  # Apply reshape
    return a

add_dimension_to_rank_one_array(a).shape

(1, 4)