# Lets import PyTorch

In [1]:
import torch
import numpy as np


## Tensors

Tensors are similar to NumPy arrays but can also be used on GPUs and CPUs


In [2]:
# Tensors are similar to NumPy arrays 
# but can also be used on GPUs (and other accelerators)

# Create a tensor from a Python list
tensor = torch.tensor([1, 2, 3, 4, 5])

tensor

tensor([1, 2, 3, 4, 5])

In [3]:
tensor.shape

torch.Size([5])

In [4]:
tensor.dtype

torch.int64

In [5]:
# We can also convert a numpy array to a tensor
numpy_array = np.array([1, 2, 3, 4, 5])
print(f"{numpy_array = }")
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_from_numpy

numpy_array = array([1, 2, 3, 4, 5])


tensor([1, 2, 3, 4, 5])

In [6]:
# We can also convert a tensor to a list
tensor_to_list = tensor_from_numpy.tolist()
tensor_to_list

[1, 2, 3, 4, 5]

In [7]:
tensor_to_numpy = tensor_from_numpy.numpy()
tensor_to_numpy

array([1, 2, 3, 4, 5])

We will retrieve many familiar functions from NumPy


In [8]:
t_ones = torch.ones((3, 4))
t_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
t_zeros = torch.zeros((3, 4))
t_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
t_rand = torch.rand((3, 4))
t_rand

tensor([[0.0300, 0.2355, 0.8756, 0.3529],
        [0.8171, 0.9409, 0.5833, 0.2204],
        [0.6704, 0.0268, 0.7159, 0.4047]])

In [11]:
# Like with numpy we can reshape tensors
t_rand.reshape(2, 6)

tensor([[0.0300, 0.2355, 0.8756, 0.3529, 0.8171, 0.9409],
        [0.5833, 0.2204, 0.6704, 0.0268, 0.7159, 0.4047]])

In [12]:
t_rand.reshape(-1, 2)

tensor([[0.0300, 0.2355],
        [0.8756, 0.3529],
        [0.8171, 0.9409],
        [0.5833, 0.2204],
        [0.6704, 0.0268],
        [0.7159, 0.4047]])

# Operations on tensors

Works the same as with numpy

In [13]:
t_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
t_ones + t_ones

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [15]:
t_ones * 5

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [16]:
t_ones[0, 0] = 100
t_ones

tensor([[100.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]])

In [17]:
t_ones[1:,2:] = 42
t_ones

tensor([[100.,   1.,   1.,   1.],
        [  1.,   1.,  42.,  42.],
        [  1.,   1.,  42.,  42.]])

# Using the GPU

In [43]:
# Let's check if cuda is available:
if torch.cuda.is_available():
    print(f"Cuda is available!")
    device = torch.device("cuda")
else:
    print(f"CUDA is not available! Let's use the CPU")
    device = torch.device("cpu")

# This device object will be used to specify where a tensor should be stored.
device

Cuda is available!


device(type='cuda')

In [44]:
# We can send data on the gpu this way:
tensor = torch.ones((3, 4))

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [45]:
tensor_on_gpu = tensor.to("cuda")
tensor_on_gpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [34]:
# We can also do some operations on the gpu
tensor_on_gpu + tensor_on_gpu

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], device='cuda:0')

In [39]:
# But be careful, only tensors on the same device can be used in operations

print(f"{tensor_on_gpu = }")
print(f"{t_ones = }")

# tensor_on_gpu + t_ones # /!\ This will raise an error

tensor_on_gpu = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
t_ones = tensor([[100.,   1.,   1.,   1.],
        [  1.,   1.,  42.,  42.],
        [  1.,   1.,  42.,  42.]])


In [41]:
# tensor_on_gpu.numpy()

In [42]:
tensor_on_gpu.to("cpu").numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [24]:
tensor_on_gpu.cpu().numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [25]:
# Once we are done with the gpu operations we can send the tensor back to the cpu
tensor_on_cpu = tensor_on_gpu.to("cpu")
tensor_on_cpu

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
# Or even to the numpy
numpy_array = tensor_on_cpu.numpy()
numpy_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)