___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>
___

In [57]:
import numpy as np

## Operations

In [58]:
a = np.full((4,), 10, dtype=float)
a

array([10., 10., 10., 10.])

In [59]:
b = np.full_like(a, 3)
b

array([3., 3., 3., 3.])

### Basic operations


In [60]:
a + b

array([13., 13., 13., 13.])

In [61]:
a * b

array([30., 30., 30., 30.])

In [62]:
a / b

array([3.33333333, 3.33333333, 3.33333333, 3.33333333])

In [63]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [64]:
c / c

/tmp/ipykernel_56372/1934242309.py:1: RuntimeWarning: invalid value encountered in divide
  c / c


array([nan,  1.,  1.,  1.])

In [65]:
a / b

array([3.33333333, 3.33333333, 3.33333333, 3.33333333])

In [66]:
a // b

array([3., 3., 3., 3.])

### Broadcasting

In [67]:
a = np.arange(1, 4)
a

array([1, 2, 3])

In [68]:
a * 2

array([2, 4, 6])


![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [69]:
a + 1

array([2, 3, 4])

In [70]:
a / 2

array([0.5, 1. , 1.5])

In [71]:
a // 2

array([0, 1, 1])

In [72]:
a

array([1, 2, 3])

In [73]:
np.zeros((4,3)) + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### Advanced operations

In [74]:
a ** 2

array([1, 4, 9])

In [75]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [76]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [77]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [78]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

#### Dot product

![](https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/matrix-representation-of-dot-product-1626103121.png)

In [79]:
a = np.arange(1, 11)
b = np.arange(4, 14)

np.dot(a, b)

550

In [80]:
a = np.arange(0, 3, .7)
a

array([0. , 0.7, 1.4, 2.1, 2.8])

In [81]:
np.floor(a)     # Rounds to lower integer

array([0., 0., 1., 2., 2.])

In [82]:
np.ceil(a)      # Rounds to upper integer

array([0., 1., 2., 3., 3.])

In [83]:
np.round(a)     # Rounds to nearest integer

array([0., 1., 1., 2., 3.])

In [84]:
# Matrix multiplication

a_2d = np.arange(12).reshape(3, -1)
b_2d = np.arange(12).reshape(-1, 3)

print(f"{a_2d.shape = }")
print(f"{b_2d.shape = }")

np.matmul(      # is equivalent to `a_2d @ b_2d``
    a_2d,
    b_2d
)

a_2d.shape = (3, 4)
b_2d.shape = (4, 3)


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

## Statistics

In [114]:
a = np.arange(5, 5 + 12, dtype=float)
a

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.])

In [115]:
a.shape

(12,)

In [116]:
a.max()

16.0

In [117]:
a.min()

5.0

In [118]:
a.argmax()

11

In [119]:
a.argmin()

0

### Sum

$$
\sum_{i=1}^n x_i
$$

In [120]:
a.sum()

126.0

### Mean

$$
\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i
$$

In [121]:
a.mean()

10.5

### Standard deviation

$$
\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^n (x_i - \bar{x})^2}
$$

In [122]:
a.std()

3.452052529534663

### Variance

$$
\sigma^2 = \frac{1}{n}\sum_{i=1}^n (x_i - \bar{x})^2
$$

In [123]:
a.var()

11.916666666666666

### Axis argument
![](https://miro.medium.com/v2/resize:fit:720/format:webp/1*jmXqsVUNaBaUsBAkHgqb3A.png)

In [124]:
a_3d = np.arange(24).reshape(2, 3, 4)
a_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
a_3d.sum()

276

In [126]:
a_3d.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [127]:
a_3d.sum(axis=1)


array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [128]:
a_3d.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## Numpy special values

In [129]:
np.NaN

nan

In [130]:
np.NaN == np.NaN

False

In [131]:
np.inf

inf

In [132]:
np.inf * -1

-inf

###  It's best to avoid rank one array 

Rank one arrays are arrays with (n,) shapes 

#### Problematic example

In [133]:
a = np.random.randn(5)
a

array([ 1.26378438, -0.28523437, -1.07667777, -0.77408528, -1.59735859])

In [134]:
a.shape # != (5, 1)

(5,)

In [135]:
# Tranpose gives back the same array on rank one error, 
#   this is source error
a.T

array([ 1.26378438, -0.28523437, -1.07667777, -0.77408528, -1.59735859])

In [ ]:
a_2d = a.reshape((5, 1))
a_2d

array([[ 1.26378438],
       [-0.28523437],
       [-1.07667777],
       [-0.77408528],
       [-1.59735859]])

In [ ]:
a_2d.T

array([[ 1.26378438, -0.28523437, -1.07667777, -0.77408528, -1.59735859]])

In [136]:
np.dot(a, a.T)

5.988507091514587

#### Expected behavior

In [137]:
a_2d = a.copy().reshape((5, 1))
a_2d

array([[ 1.26378438],
       [-0.28523437],
       [-1.07667777],
       [-0.77408528],
       [-1.59735859]])

In [138]:
a_2d.shape

(5, 1)

In [139]:
a_2d.T

array([[ 1.26378438, -0.28523437, -1.07667777, -0.77408528, -1.59735859]])

In [140]:
np.dot(a_2d.T, a_2d)

array([[5.98850709]])

In [141]:
np.dot(a_2d, a_2d.T)

array([[ 1.59715096, -0.36047474, -1.36068854, -0.97827688, -2.01871683],
       [-0.36047474,  0.08135865,  0.30710551,  0.22079573,  0.45562157],
       [-1.36068854,  0.30710551,  1.15923501,  0.83344041,  1.71984047],
       [-0.97827688,  0.22079573,  0.83344041,  0.59920802,  1.23649176],
       [-2.01871683,  0.45562157,  1.71984047,  1.23649176,  2.55155445]])

#### Function to solve the problem of shape (n,)

In [142]:
def add_dimension_to_rank_one_array(a: np.ndarray):
    if len(a.shape) == 1:       # Check if rank one array
        a = a.reshape((1, -1))  # Apply reshape
    return a

add_dimension_to_rank_one_array(a).shape

(1, 5)